# Generated by Django 4.1.3 on 2022-11-27 18:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='pars', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
