# Generated by Django 4.1.3 on 2022-11-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0003_comment_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
