# Generated by Django 4.1.3 on 2022-11-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0004_comment_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
