# Generated by Django 4.1.3 on 2022-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0006_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
