# Generated by Django 4.1.3 on 2022-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManager', '0007_comment_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='explanation',
            field=models.TextField(default=None, null=True),
        ),
    ]
