# Generated by Django 4.1.3 on 2022-11-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_authtoken_id_authtoken_token_authtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='life',
            field=models.DateTimeField(null=True),
        ),
    ]
