# Generated by Django 4.1.3 on 2022-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_authtoken_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='life',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
