# Generated by Django 4.1.3 on 2022-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_authtoken_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='usage',
            field=models.TextField(default='None', null=True),
        ),
    ]
